eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10   # DO NOT DO THIS IN PRODUCTION
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  leaseRenewalIntervalInSeconds: 5

server:
  port: 6969

spring:
  cloud:
    vault:
      authentication: TOKEN
      token: 00000000-0000-0000-0000-000000000000
